"""user validations

Revision ID: 25a37ba217b0
Revises: 1669077f7880
Create Date: 2024-03-02 10:26:01.786162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25a37ba217b0'
down_revision = '1669077f7880'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plant_cares', schema=None) as batch_op:
        batch_op.add_column(sa.Column('purchased_plants_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_plant_cares_user_id_users', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_plant_cares_purchased_plants_id_purchased_plants'), 'purchased_plants', ['purchased_plants_id'], ['id'])
        batch_op.drop_column('user_id')

    with op.batch_alter_table('purchased_plants', schema=None) as batch_op:
        batch_op.alter_column('purchased_on',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(),
               existing_nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('first_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('first_name',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('purchased_plants', schema=None) as batch_op:
        batch_op.alter_column('purchased_on',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    with op.batch_alter_table('plant_cares', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_plant_cares_purchased_plants_id_purchased_plants'), type_='foreignkey')
        batch_op.create_foreign_key('fk_plant_cares_user_id_users', 'users', ['user_id'], ['id'])
        batch_op.drop_column('purchased_plants_id')

    # ### end Alembic commands ###
