"""removed purchased

Revision ID: b275ca8789c1
Revises: d90710f6c619
Create Date: 2024-03-05 15:10:31.447750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b275ca8789c1'
down_revision = 'd90710f6c619'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchased_plants', schema=None) as batch_op:
        batch_op.drop_column('purchased_from')
        batch_op.drop_column('purchased_on')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchased_plants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('purchased_on', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('purchased_from', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
