"""plantcare changes

Revision ID: d90710f6c619
Revises: 64e0746a7a2e
Create Date: 2024-03-02 13:28:16.466712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd90710f6c619'
down_revision = '64e0746a7a2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plant_cares', schema=None) as batch_op:
        batch_op.add_column(sa.Column('purchased_plant_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_plant_cares_purchased_plants_id_purchased_plants', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_plant_cares_purchased_plant_id_purchased_plants'), 'purchased_plants', ['purchased_plant_id'], ['id'])
        batch_op.drop_column('plant')
        batch_op.drop_column('purchased_plants_id')

    with op.batch_alter_table('purchased_plants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchased_plants', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('plant_cares', schema=None) as batch_op:
        batch_op.add_column(sa.Column('purchased_plants_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('plant', sa.VARCHAR(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_plant_cares_purchased_plant_id_purchased_plants'), type_='foreignkey')
        batch_op.create_foreign_key('fk_plant_cares_purchased_plants_id_purchased_plants', 'purchased_plants', ['purchased_plants_id'], ['id'])
        batch_op.drop_column('purchased_plant_id')

    # ### end Alembic commands ###
