"""empty message

Revision ID: eb08f889e363
Revises: d90710f6c619
Create Date: 2024-03-05 14:00:27.354807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb08f889e363'
down_revision = 'd90710f6c619'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plant_cares', schema=None) as batch_op:
        batch_op.alter_column('purchased_plant_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plant_cares', schema=None) as batch_op:
        batch_op.alter_column('purchased_plant_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
